#cloud-config

coreos:
    etcd:
        name: node002
        discovery: https://discovery.etcd.io/ad926b84189e8a1a5034a6de90417a8b
        addr: 192.99.39.57:4001
        peer-addr: 172.16.0.2:7001

    fleet:
        public-ip: 192.99.39.57
        metadata: region=us-east

    update:
        reboot-strategy: etcd-lock

    units:
      - name: etcd.service
        command: start

      - name: fleet.service
        command: start

      - name: sshd.socket
        command: restart
        content: |
            [Socket]
            ListenStream=2222
            Accept=yes

    users:
      - name: styles
        groups:
          - sudo
          - docker
        ssh_authorized_keys: 
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWCV0IbLAh+Lh8/gGsV6Qrs+4A2Yvwex8vEm8tPLLMdqNNF3L6vLTsAmGOUOk6YrdJQx0PV0zN09Bi/MrH/EsEMNRNO+qggPkLim0BAmUmcoROd3GQdHWF/BpgT7lwz80MqzlW+HMwzKgaax/tE3SxycdCgATvk8WGWVvlKtv6ahFn0moIstOFzFAuJiI5XHqWLCVHBDd0xHZ3Fv6qPkX9X9qb2G1ys29uScU1PGnVwPbwkrP1JcBwos/rUW4EPD3L3ONfWpilXoN8ljzbldxgdP7pbTOKvXUhZ4gK5RxWxbXOLWgYg53EZk81j5zcw947pE99oOXwYCN5m8urwzdD styles@styles-laptop
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgPYlaLm3WXWmsQJ4jJ9E2PLK7mynuDgF6CoRmCv/XlcHMY2MgrMHRdYjXBXlS77xhsD0i9xjtXSoIi+2QLodllka6Zm4xXAuPq23tV5GK8ronVMbUs4EWvH+lnyQ+hjYw4gHed2u9Evwdh4yNRqb8tcuCBz2xFlXOitButgK5CJZn0LebgutqLzhWM6pctg6UMr9kWfqeATE1H5W0+mvSJXtbzYiNQCevzaJ676a04F1P3jVLoeyE9pqX6A+Wr6gngj+XbMqMiAwV9kAPc1Mo0OHixF/ZmH2DWYJ8wmr/1enQkTY/gVK0UTtPSyMYw9ss7VGUC+pNQUEOdxD3GhBJ styles@styles-desktop

ssh_authorized_keys: 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWCV0IbLAh+Lh8/gGsV6Qrs+4A2Yvwex8vEm8tPLLMdqNNF3L6vLTsAmGOUOk6YrdJQx0PV0zN09Bi/MrH/EsEMNRNO+qggPkLim0BAmUmcoROd3GQdHWF/BpgT7lwz80MqzlW+HMwzKgaax/tE3SxycdCgATvk8WGWVvlKtv6ahFn0moIstOFzFAuJiI5XHqWLCVHBDd0xHZ3Fv6qPkX9X9qb2G1ys29uScU1PGnVwPbwkrP1JcBwos/rUW4EPD3L3ONfWpilXoN8ljzbldxgdP7pbTOKvXUhZ4gK5RxWxbXOLWgYg53EZk81j5zcw947pE99oOXwYCN5m8urwzdD styles@styles-laptop
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgPYlaLm3WXWmsQJ4jJ9E2PLK7mynuDgF6CoRmCv/XlcHMY2MgrMHRdYjXBXlS77xhsD0i9xjtXSoIi+2QLodllka6Zm4xXAuPq23tV5GK8ronVMbUs4EWvH+lnyQ+hjYw4gHed2u9Evwdh4yNRqb8tcuCBz2xFlXOitButgK5CJZn0LebgutqLzhWM6pctg6UMr9kWfqeATE1H5W0+mvSJXtbzYiNQCevzaJ676a04F1P3jVLoeyE9pqX6A+Wr6gngj+XbMqMiAwV9kAPc1Mo0OHixF/ZmH2DWYJ8wmr/1enQkTY/gVK0UTtPSyMYw9ss7VGUC+pNQUEOdxD3GhBJ styles@styles-desktop



